# inspect_Asp.pml  (generated by make_pymol.py)
# 9 plausible-binuclear PPOs (Asp substitutions) overlaid on PmTYR (B2ZB02).
# CIFs are PRE-ALIGNED onto PmTYR (prealign.py baked the transforms) -> no super.
# Only ONE structure is shown at a time so PyMOL never renders them all at once.
#     show_only <name>     e.g.  show_only 1_H1Asp_A0ABQ6N7K7
#     show_all             overlay every structure
#     show_only PmTYR      reference only
# RUN FROM THIS FOLDER:  cd <plausible_binuclear>; @inspect_Asp.pml
reinitialize
bg_color white
set ray_shadows, 0
set orthoscopic, 1
set_color pastelblue, [0.65, 0.78, 0.95]

# Everything is built inside ONE atomic python block, with each object
# DISABLED as it loads, so PyMOL never tessellates/renders a cartoon until
# show_only enables it. Building with objects enabled lets the GUI redraw
# every enabled cartoon on each load (O(n^2)) -> the slow buffering.
python
from pymol import cmd

cmd.load("PmTYR_B2ZB02.cif", "PmTYR")
cmd.disable("PmTYR")
cmd.hide("everything", "PmTYR")
cmd.show("cartoon", "PmTYR")
cmd.color("gray90", "PmTYR")
cmd.show("sticks", "PmTYR and resi 42+60+69+204+208+231 and not name N+O+C")
cmd.color("gray60", "PmTYR and resi 42+60+69+204+208+231")

data = [
    ("1_H1Asp_A0ABQ6N7K7", 91),
    ("2_H2Asp_A0A9E7H3J2", 121),
    ("2_H2Asp_A0A9P4H2P0", 117),
    ("3_H3Asp_A0A9P4PM19", 111),
    ("3_H3Asp_A0ABQ9S7H6", 120),
    ("6_H6Asp_A0A3Q3L0Y4", 389),
    ("6_H6Asp_A0A914L211", 320),
    ("6_H6Asp_A0A9Q3GXD1", 372),
    ("6_H6Asp_C8CHT1", 192),
]
for obj, resi in data:
    cmd.load(obj + ".cif", obj)
    cmd.disable(obj)                  # stay hidden during build -> no render
    cmd.hide("everything", obj)
    cmd.show("cartoon", obj)
    cmd.color("gray90", obj)
    sel = f"({obj}) and resi {resi}"
    cmd.show("sticks", sel + " and not name N+O+C")   # the substituted residue
    cmd.color("pastelblue", sel)

def show_only(key):
    for k in cmd.get_names('objects'):
        cmd.disable(k)
    cmd.enable('PmTYR')
    if key != 'PmTYR':
        cmd.enable(key)
    cmd.zoom('PmTYR and resi 42+60+69+204+208+231', 8)
cmd.extend('show_only', show_only)

def show_all(*a):
    for k in cmd.get_names('objects'):
        cmd.enable(k)
    cmd.zoom('PmTYR and resi 42+60+69+204+208+231', 8)
cmd.extend('show_all', show_all)

print('structures (use:  show_only <name>):')
for obj, _ in data:
    print('   ', obj)

# start with only the reference + first structure shown
show_only('1_H1Asp_A0ABQ6N7K7')
python end

