# inspect_plausible_binuclear.pml  (generated by make_pymol.py)
# 66 plausible-binuclear PPOs (all 5 substitution types) overlaid on PmTYR (B2ZB02).
# CIFs are PRE-ALIGNED onto PmTYR (prealign.py baked the transforms) -> no super.
# Only ONE structure is shown at a time so PyMOL never renders them all at once.
#     show_only <name>     e.g.  show_only 1_H1Asp_A0ABQ6N7K7
#     show_all             overlay every structure
#     show_only PmTYR      reference only
# RUN FROM THIS FOLDER:  cd <plausible_binuclear>; @inspect_plausible_binuclear.pml
reinitialize
bg_color white
set ray_shadows, 0
set orthoscopic, 1
set_color pastelblue, [0.65, 0.78, 0.95]

# Everything is built inside ONE atomic python block, with each object
# DISABLED as it loads, so PyMOL never tessellates/renders a cartoon until
# show_only enables it. Building with objects enabled lets the GUI redraw
# every enabled cartoon on each load (O(n^2)) -> the slow buffering.
python
from pymol import cmd

cmd.load("PmTYR_B2ZB02.cif", "PmTYR")
cmd.disable("PmTYR")
cmd.hide("everything", "PmTYR")
cmd.show("cartoon", "PmTYR")
cmd.color("gray90", "PmTYR")
cmd.show("sticks", "PmTYR and resi 42+60+69+204+208+231 and not name N+O+C")
cmd.color("gray60", "PmTYR and resi 42+60+69+204+208+231")

data = [
    ("1_H1Asp_A0ABQ6N7K7", 91),
    ("1_H1Cys_A0A0C2WPB2", 130),
    ("1_H1Tyr_A0A0D6LZL4", 142),
    ("1_H1Tyr_A0A1U7LR42", 88),
    ("1_H1Tyr_A0A4R8RI59", 101),
    ("1_H1Tyr_A0AA39T9Y6", 83),
    ("1_H1Tyr_A0AA40K7X1", 23),
    ("2_H2Asp_A0A9E7H3J2", 121),
    ("2_H2Asp_A0A9P4H2P0", 117),
    ("2_H2Cys_A0A9P6EYF3", 65),
    ("2_H2Glu_A0A9N9PT18", 89),
    ("2_H2Tyr_A0A5C6SKB8", 77),
    ("2_H2Tyr_A0A7S4QPD7", 280),
    ("2_H2Tyr_A0A7S4QRZ1", 280),
    ("2_H2Tyr_A0A8H7K265", 116),
    ("2_H2Tyr_A0A8X7N2K2", 140),
    ("2_H2Tyr_A0ACC2HR65", 139),
    ("2_H2Tyr_N1RKC9", 83),
    ("2_H2Tyr_X0JGY5", 78),
    ("3_H3Asp_A0A9P4PM19", 111),
    ("3_H3Asp_A0ABQ9S7H6", 120),
    ("3_H3Tyr_A0A2J6TC85", 60),
    ("3_H3Tyr_A0A4Y8D0D0", 91),
    ("3_H3Tyr_A0A507F697", 89),
    ("3_H3Tyr_A0A5N5QEZ6", 116),
    ("3_H3Tyr_A0AA39K704", 108),
    ("3_H3Tyr_A0AAE0NPZ1", 72),
    ("4_H4Cys_A0A915M8S0", 245),
    ("4_H4Glu_A0A6A3HLB0", 184),
    ("4_H4Glu_A0A6A3Q4B5", 184),
    ("4_H4Glu_A0A6G0QFF2", 184),
    ("4_H4Glu_A0AAW2WSM8", 292),
    ("4_H4Met_A0A091TMG5", 268),
    ("4_H4Met_A0ABR0H9K2", 267),
    ("4_H4Met_A0ABR0I6B4", 267),
    ("4_H4Tyr_A0A1Y2HIE7", 189),
    ("4_H4Tyr_A0A7J6UTM6", 328),
    ("4_H4Tyr_A0ABR1TI72", 211),
    ("4_H4Tyr_E5Q8T0", 327),
    ("5_H5Cys_A0A395HJP7", 240),
    ("5_H5Cys_A0A8H7CJP5", 249),
    ("5_H5Tyr_A0A0G4N7R0", 322),
    ("5_H5Tyr_A0A1Y2EAK7", 215),
    ("5_H5Tyr_A0A444RJX5", 196),
    ("5_H5Tyr_A0A9P7QPY3", 230),
    ("5_H5Tyr_F6G5J6", 231),
    ("6_H6Asp_A0A3Q3L0Y4", 389),
    ("6_H6Asp_A0A914L211", 320),
    ("6_H6Asp_A0A9Q3GXD1", 372),
    ("6_H6Asp_C8CHT1", 192),
    ("6_H6Cys_A0A9N9LFQ9", 348),
    ("6_H6Cys_A0A9Q0QJI7", 343),
    ("6_H6Cys_A0ABD1WHD2", 351),
    ("6_H6Cys_A0ABR4K145", 332),
    ("6_H6Glu_A0AAD5XR56", 234),
    ("6_H6Met_A0A0L6VTF1", 369),
    ("6_H6Met_A0A9W4KMZ8", 383),
    ("6_H6Tyr_A0A0L0VSP3", 347),
    ("6_H6Tyr_A0A0L0VSW2", 287),
    ("6_H6Tyr_A0A2N5TV63", 417),
    ("6_H6Tyr_A0A2S4UTV9", 287),
    ("6_H6Tyr_A0A2S4VEY7", 287),
    ("6_H6Tyr_A0A9N8JDS5", 578),
    ("6_H6Tyr_A0A9P8SF21", 297),
    ("6_H6Tyr_A0AA38ZJU6", 375),
    ("6_H6Tyr_A0ABR3QSB3", 311),
]
for obj, resi in data:
    cmd.load(obj + ".cif", obj)
    cmd.disable(obj)                  # stay hidden during build -> no render
    cmd.hide("everything", obj)
    cmd.show("cartoon", obj)
    cmd.color("gray90", obj)
    sel = f"({obj}) and resi {resi}"
    cmd.show("sticks", sel + " and not name N+O+C")   # the substituted residue
    cmd.color("pastelblue", sel)

def show_only(key):
    for k in cmd.get_names('objects'):
        cmd.disable(k)
    cmd.enable('PmTYR')
    if key != 'PmTYR':
        cmd.enable(key)
    cmd.zoom('PmTYR and resi 42+60+69+204+208+231', 8)
cmd.extend('show_only', show_only)

def show_all(*a):
    for k in cmd.get_names('objects'):
        cmd.enable(k)
    cmd.zoom('PmTYR and resi 42+60+69+204+208+231', 8)
cmd.extend('show_all', show_all)

print('structures (use:  show_only <name>):')
for obj, _ in data:
    print('   ', obj)

# start with only the reference + first structure shown
show_only('1_H1Asp_A0ABQ6N7K7')
python end

