#!/usr/bin/env python3
"""Generate per-mutation-type PyMOL inspection scripts from pb66_resnum.tsv.

One script per substituted-residue type (Tyr/Asp/Cys/Glu/Met) plus a combined
one. Each loads PmTYR (B2ZB02) as the reference and overlays that type's
plausible-binuclear structures, whose CIF coords are ALREADY pre-aligned onto
PmTYR by prealign.py (no `super` at load).

To stay fast with many objects, only ONE structure is DISPLAYED at a time using
PyMOL's disable/enable (the proven pattern from pymol_variants_active_site.py).
Building all cartoons costs nothing visually until enabled; rendering them all at
once was what made the old all-66 script buffer. Use:
    show_only <name>   one structure (+ PmTYR)
    show_all           overlay every structure
    show_only PmTYR    reference only
"""
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))
rows = list(csv.DictReader(open(os.path.join(HERE, "pb66_resnum.tsv")), delimiter="\t"))

ANCHORS = "42+60+69+204+208+231"

entries = []  # (seqidx, res, stem, resi)
for r in rows:
    si = int(r["seqidx"]); res = r["new_res"].capitalize(); acc = r["accession"]
    stem = f"{si}_H{si}{res}_{acc}"
    entries.append((si, res, stem, r["auth_seq"]))
entries.sort(key=lambda e: (e[0], e[1], e[2]))


def emit(subset, outfile, title):
    lines = [
        f"# {outfile}  (generated by make_pymol.py)",
        f"# {len(subset)} plausible-binuclear PPOs ({title}) overlaid on PmTYR (B2ZB02).",
        "# CIFs are PRE-ALIGNED onto PmTYR (prealign.py baked the transforms) -> no super.",
        "# Only ONE structure is shown at a time so PyMOL never renders them all at once.",
        f"#     show_only <name>     e.g.  show_only {subset[0][2]}",
        "#     show_all             overlay every structure",
        "#     show_only PmTYR      reference only",
        f"# RUN FROM THIS FOLDER:  cd <plausible_binuclear>; @{outfile}",
        "reinitialize",
        "bg_color white",
        "set ray_shadows, 0",
        "set orthoscopic, 1",
        "set_color pastelblue, [0.65, 0.78, 0.95]",
        "",
        "# Everything is built inside ONE atomic python block, with each object",
        "# DISABLED as it loads, so PyMOL never tessellates/renders a cartoon until",
        "# show_only enables it. Building with objects enabled lets the GUI redraw",
        "# every enabled cartoon on each load (O(n^2)) -> the slow buffering.",
        "python",
        "from pymol import cmd",
        "",
        f'cmd.load("PmTYR_B2ZB02.cif", "PmTYR")',
        'cmd.disable("PmTYR")',
        'cmd.hide("everything", "PmTYR")',
        'cmd.show("cartoon", "PmTYR")',
        'cmd.color("gray90", "PmTYR")',
        f'cmd.show("sticks", "PmTYR and resi {ANCHORS} and not name N+O+C")',
        f'cmd.color("gray60", "PmTYR and resi {ANCHORS}")',
        "",
        "data = [",
    ]
    for si, res, stem, resi in subset:
        lines.append(f'    ("{stem}", {resi}),')
    lines += [
        "]",
        "for obj, resi in data:",
        '    cmd.load(obj + ".cif", obj)',
        '    cmd.disable(obj)                  # stay hidden during build -> no render',
        '    cmd.hide("everything", obj)',
        '    cmd.show("cartoon", obj)',
        '    cmd.color("gray90", obj)',
        '    sel = f"({obj}) and resi {resi}"',
        '    cmd.show("sticks", sel + " and not name N+O+C")   # the substituted residue',
        '    cmd.color("pastelblue", sel)',
        "",
        "def show_only(key):",
        "    for k in cmd.get_names('objects'):",
        "        cmd.disable(k)",
        "    cmd.enable('PmTYR')",
        "    if key != 'PmTYR':",
        "        cmd.enable(key)",
        f"    cmd.zoom('PmTYR and resi {ANCHORS}', 8)",
        "cmd.extend('show_only', show_only)",
        "",
        "def show_all(*a):",
        "    for k in cmd.get_names('objects'):",
        "        cmd.enable(k)",
        f"    cmd.zoom('PmTYR and resi {ANCHORS}', 8)",
        "cmd.extend('show_all', show_all)",
        "",
        "print('structures (use:  show_only <name>):')",
        "for obj, _ in data:",
        "    print('   ', obj)",
        "",
        "# start with only the reference + first structure shown",
        f"show_only('{subset[0][2]}')",
        "python end",
        "",
    ]
    with open(os.path.join(HERE, outfile), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {outfile} ({len(subset)} structures)")


by_res = {}
for e in entries:
    by_res.setdefault(e[1], []).append(e)

for res, subset in sorted(by_res.items()):
    emit(subset, f"inspect_{res}.pml", f"{res} substitutions")
emit(entries, "inspect_plausible_binuclear.pml", "all 5 substitution types")
